// <auto-generated />
using System;
using Inmobiliaria.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inmobiliaria.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Inmobiliaria.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropiedadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPropiedad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.ImagenPropiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AceptaMascotas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AntiguedadAnos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AptoProfesional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarrioCiudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CercaDe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Depto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntreCalle1")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntreCalle2")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EsAEstrenar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsBarrioCerradoOrCountry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpensasMonto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpensasTipo")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Moneda")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoPublicarPrecio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NroCalle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartidoLocalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Piso")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PropiedadOcupada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCosta")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPendiente")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVista")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisibilidadDireccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZonaGeografica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Propiedades");

                    b.HasDiscriminator<string>("Tipo").HasValue("Propiedad");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Casa", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<string>("AguaCaliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calefaccion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CantidadBanos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadDormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasCubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasDescubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasSemicubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Edificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FondoLibre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instalaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luminosidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoAncho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoLargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plantas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicios")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieCubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieDescubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTerreno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPiso")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTecho")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVigilancia")
                        .HasColumnType("TEXT");

                    b.ToTable("Propiedades", t =>
                        {
                            t.Property("AguaCaliente")
                                .HasColumnName("Casa_AguaCaliente");

                            t.Property("Calefaccion")
                                .HasColumnName("Casa_Calefaccion");

                            t.Property("CantidadBanos")
                                .HasColumnName("Casa_CantidadBanos");

                            t.Property("CantidadDormitorios")
                                .HasColumnName("Casa_CantidadDormitorios");

                            t.Property("CocherasCubiertas")
                                .HasColumnName("Casa_CocherasCubiertas");

                            t.Property("CocherasDescubiertas")
                                .HasColumnName("Casa_CocherasDescubiertas");

                            t.Property("CocherasSemicubiertas")
                                .HasColumnName("Casa_CocherasSemicubiertas");

                            t.Property("Edificacion")
                                .HasColumnName("Casa_Edificacion");

                            t.Property("FondoLibre")
                                .HasColumnName("Casa_FondoLibre");

                            t.Property("Luminosidad")
                                .HasColumnName("Casa_Luminosidad");

                            t.Property("MedidasTerrenoAncho")
                                .HasColumnName("Casa_MedidasTerrenoAncho");

                            t.Property("MedidasTerrenoLargo")
                                .HasColumnName("Casa_MedidasTerrenoLargo");

                            t.Property("Orientacion")
                                .HasColumnName("Casa_Orientacion");

                            t.Property("Plantas")
                                .HasColumnName("Casa_Plantas");

                            t.Property("SuperficieCubierta")
                                .HasColumnName("Casa_SuperficieCubierta");

                            t.Property("SuperficieDescubierta")
                                .HasColumnName("Casa_SuperficieDescubierta");

                            t.Property("SuperficieTerreno")
                                .HasColumnName("Casa_SuperficieTerreno");

                            t.Property("SuperficieTotal")
                                .HasColumnName("Casa_SuperficieTotal");

                            t.Property("TipoPiso")
                                .HasColumnName("Casa_TipoPiso");

                            t.Property("TipoTecho")
                                .HasColumnName("Casa_TipoTecho");

                            t.Property("TipoVigilancia")
                                .HasColumnName("Casa_TipoVigilancia");
                        });

                    b.HasDiscriminator().HasValue("Casa");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Departamento", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<string>("AguaCaliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmenitiesEdificio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AscensoresPrincipales")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AscensoresServicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calefaccion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CantidadBanos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadDormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadPisosEdificio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriaEdificio")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CocheraOptativa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasCubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasDescubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasSemicubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeptosPorPiso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Disposicion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FondoLibre")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalacionesPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luminosidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plantas")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosEdificio")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieCubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieDescubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoBalcon")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEdificio")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPiso")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVigilancia")
                        .HasColumnType("TEXT");

                    b.ToTable("Propiedades", t =>
                        {
                            t.Property("AguaCaliente")
                                .HasColumnName("Departamento_AguaCaliente");

                            t.Property("AmenitiesEdificio")
                                .HasColumnName("Departamento_AmenitiesEdificio");

                            t.Property("Calefaccion")
                                .HasColumnName("Departamento_Calefaccion");

                            t.Property("CantidadBanos")
                                .HasColumnName("Departamento_CantidadBanos");

                            t.Property("CantidadDormitorios")
                                .HasColumnName("Departamento_CantidadDormitorios");

                            t.Property("CocherasCubiertas")
                                .HasColumnName("Departamento_CocherasCubiertas");

                            t.Property("CocherasDescubiertas")
                                .HasColumnName("Departamento_CocherasDescubiertas");

                            t.Property("CocherasSemicubiertas")
                                .HasColumnName("Departamento_CocherasSemicubiertas");

                            t.Property("Disposicion")
                                .HasColumnName("Departamento_Disposicion");

                            t.Property("Edificacion")
                                .HasColumnName("Departamento_Edificacion");

                            t.Property("FondoLibre")
                                .HasColumnName("Departamento_FondoLibre");

                            t.Property("InstalacionesPropiedad")
                                .HasColumnName("Departamento_InstalacionesPropiedad");

                            t.Property("Luminosidad")
                                .HasColumnName("Departamento_Luminosidad");

                            t.Property("Orientacion")
                                .HasColumnName("Departamento_Orientacion");

                            t.Property("Plantas")
                                .HasColumnName("Departamento_Plantas");

                            t.Property("ServiciosEdificio")
                                .HasColumnName("Departamento_ServiciosEdificio");

                            t.Property("ServiciosPropiedad")
                                .HasColumnName("Departamento_ServiciosPropiedad");

                            t.Property("SuperficieCubierta")
                                .HasColumnName("Departamento_SuperficieCubierta");

                            t.Property("SuperficieDescubierta")
                                .HasColumnName("Departamento_SuperficieDescubierta");

                            t.Property("SuperficieTotal")
                                .HasColumnName("Departamento_SuperficieTotal");

                            t.Property("TipoPiso")
                                .HasColumnName("Departamento_TipoPiso");

                            t.Property("TipoVigilancia")
                                .HasColumnName("Departamento_TipoVigilancia");
                        });

                    b.HasDiscriminator().HasValue("Departamento");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Emprendimiento", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<int?>("CantidadAscensores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadCuotas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadDepartamentos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadPisos")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ConFinanciacion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepartamentosPorPiso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionFinanciacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtapaObra")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("Financia")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaAdministra")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaComercializa")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaConstruye")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaDirige")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalacionesPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeyendaComercial")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoEmprendimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaginaWeb")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanosUrls")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PorcentajeAnticipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosPropiedad")
                        .HasColumnType("TEXT");

                    b.ToTable("Propiedades", t =>
                        {
                            t.Property("InstalacionesPropiedad")
                                .HasColumnName("Emprendimiento_InstalacionesPropiedad");

                            t.Property("ServiciosPropiedad")
                                .HasColumnName("Emprendimiento_ServiciosPropiedad");
                        });

                    b.HasDiscriminator().HasValue("Emprendimiento");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Galpon", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<decimal?>("AlturaEntrada")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AlturaTecho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AnchoEntrada")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AreaDeposito")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AreaOficinas")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CantidadBanos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadColumnas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadDormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadNaves")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cocheras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoHabilitacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EspacioEstacionamiento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FondoLibre")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fos")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fot")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalacionesPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luminosidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoAncho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoLargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieConstruible")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieCubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieDescubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTerreno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoGalpon")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoGas")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPorton")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTecho")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTechoIndustrial")
                        .HasColumnType("TEXT");

                    b.ToTable("Propiedades", t =>
                        {
                            t.Property("CantidadBanos")
                                .HasColumnName("Galpon_CantidadBanos");

                            t.Property("CantidadDormitorios")
                                .HasColumnName("Galpon_CantidadDormitorios");

                            t.Property("FondoLibre")
                                .HasColumnName("Galpon_FondoLibre");

                            t.Property("InstalacionesPropiedad")
                                .HasColumnName("Galpon_InstalacionesPropiedad");

                            t.Property("Luminosidad")
                                .HasColumnName("Galpon_Luminosidad");

                            t.Property("MedidasTerrenoAncho")
                                .HasColumnName("Galpon_MedidasTerrenoAncho");

                            t.Property("MedidasTerrenoLargo")
                                .HasColumnName("Galpon_MedidasTerrenoLargo");

                            t.Property("ServiciosPropiedad")
                                .HasColumnName("Galpon_ServiciosPropiedad");

                            t.Property("SuperficieCubierta")
                                .HasColumnName("Galpon_SuperficieCubierta");

                            t.Property("SuperficieDescubierta")
                                .HasColumnName("Galpon_SuperficieDescubierta");

                            t.Property("SuperficieTerreno")
                                .HasColumnName("Galpon_SuperficieTerreno");

                            t.Property("SuperficieTotal")
                                .HasColumnName("Galpon_SuperficieTotal");

                            t.Property("TipoTecho")
                                .HasColumnName("Galpon_TipoTecho");
                        });

                    b.HasDiscriminator().HasValue("Galpon");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Local", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<decimal?>("AlturaInterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmenitiesEdificio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CantidadBanos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadDormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasCubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasDescubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasSemicubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstalacionesPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luminosidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoAncho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoLargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plantas")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosEdificio")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situado")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieCubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieDescubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieEntrepiso")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieLocal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieSubsuelo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoDestino")
                        .HasColumnType("TEXT");

                    b.ToTable("Propiedades", t =>
                        {
                            t.Property("AmenitiesEdificio")
                                .HasColumnName("Local_AmenitiesEdificio");

                            t.Property("CantidadBanos")
                                .HasColumnName("Local_CantidadBanos");

                            t.Property("CantidadDormitorios")
                                .HasColumnName("Local_CantidadDormitorios");

                            t.Property("CocherasCubiertas")
                                .HasColumnName("Local_CocherasCubiertas");

                            t.Property("CocherasDescubiertas")
                                .HasColumnName("Local_CocherasDescubiertas");

                            t.Property("CocherasSemicubiertas")
                                .HasColumnName("Local_CocherasSemicubiertas");

                            t.Property("InstalacionesPropiedad")
                                .HasColumnName("Local_InstalacionesPropiedad");

                            t.Property("Luminosidad")
                                .HasColumnName("Local_Luminosidad");

                            t.Property("MedidasTerrenoAncho")
                                .HasColumnName("Local_MedidasTerrenoAncho");

                            t.Property("MedidasTerrenoLargo")
                                .HasColumnName("Local_MedidasTerrenoLargo");

                            t.Property("Orientacion")
                                .HasColumnName("Local_Orientacion");

                            t.Property("Plantas")
                                .HasColumnName("Local_Plantas");

                            t.Property("ServiciosEdificio")
                                .HasColumnName("Local_ServiciosEdificio");

                            t.Property("ServiciosPropiedad")
                                .HasColumnName("Local_ServiciosPropiedad");

                            t.Property("SuperficieCubierta")
                                .HasColumnName("Local_SuperficieCubierta");

                            t.Property("SuperficieDescubierta")
                                .HasColumnName("Local_SuperficieDescubierta");

                            t.Property("SuperficieTotal")
                                .HasColumnName("Local_SuperficieTotal");
                        });

                    b.HasDiscriminator().HasValue("Local");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.PH", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<string>("AguaCaliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmenitiesEdificio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calefaccion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CantidadBanos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadDormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasCubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasDescubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasSemicubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Disposicion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FondoLibre")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalacionesPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luminosidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoAncho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoLargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plantas")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosEdificio")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiciosPropiedad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieCubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieDescubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTerreno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPiso")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTecho")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVigilancia")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PH");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Quinta", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<string>("AguaCaliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calefaccion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CantidadBanos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadDormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasCubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasDescubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocherasSemicubiertas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetalleAcceso")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DistanciaPavimentoKm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FondoLibre")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaTerreno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instalaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luminosidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoAncho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoLargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plantas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicios")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieCubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieDescubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTerreno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPiso")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTecho")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadSuperficieTotal")
                        .HasColumnType("TEXT");

                    b.ToTable("Propiedades", t =>
                        {
                            t.Property("AguaCaliente")
                                .HasColumnName("Quinta_AguaCaliente");

                            t.Property("Calefaccion")
                                .HasColumnName("Quinta_Calefaccion");

                            t.Property("CantidadBanos")
                                .HasColumnName("Quinta_CantidadBanos");

                            t.Property("CantidadDormitorios")
                                .HasColumnName("Quinta_CantidadDormitorios");

                            t.Property("CocherasCubiertas")
                                .HasColumnName("Quinta_CocherasCubiertas");

                            t.Property("CocherasDescubiertas")
                                .HasColumnName("Quinta_CocherasDescubiertas");

                            t.Property("CocherasSemicubiertas")
                                .HasColumnName("Quinta_CocherasSemicubiertas");

                            t.Property("Edificacion")
                                .HasColumnName("Quinta_Edificacion");

                            t.Property("FondoLibre")
                                .HasColumnName("Quinta_FondoLibre");

                            t.Property("Instalaciones")
                                .HasColumnName("Quinta_Instalaciones");

                            t.Property("Luminosidad")
                                .HasColumnName("Quinta_Luminosidad");

                            t.Property("MedidasTerrenoAncho")
                                .HasColumnName("Quinta_MedidasTerrenoAncho");

                            t.Property("MedidasTerrenoLargo")
                                .HasColumnName("Quinta_MedidasTerrenoLargo");

                            t.Property("Orientacion")
                                .HasColumnName("Quinta_Orientacion");

                            t.Property("Plantas")
                                .HasColumnName("Quinta_Plantas");

                            t.Property("Servicios")
                                .HasColumnName("Quinta_Servicios");

                            t.Property("SuperficieCubierta")
                                .HasColumnName("Quinta_SuperficieCubierta");

                            t.Property("SuperficieDescubierta")
                                .HasColumnName("Quinta_SuperficieDescubierta");

                            t.Property("SuperficieTerreno")
                                .HasColumnName("Quinta_SuperficieTerreno");

                            t.Property("SuperficieTotal")
                                .HasColumnName("Quinta_SuperficieTotal");

                            t.Property("TipoPiso")
                                .HasColumnName("Quinta_TipoPiso");

                            t.Property("TipoTecho")
                                .HasColumnName("Quinta_TipoTecho");
                        });

                    b.HasDiscriminator().HasValue("Quinta");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Terreno", b =>
                {
                    b.HasBaseType("Inmobiliaria.Api.Models.Propiedad");

                    b.Property<string>("DetalleAcceso")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaTerreno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FosPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FotPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instalaciones")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoAncho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MedidasTerrenoLargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicios")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieConstruibleMetros")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieCubierta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuperficieTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEstructuraTerreno")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoLote")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsoTerreno")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoZona")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadSuperficieTotal")
                        .HasColumnType("TEXT");

                    b.ToTable("Propiedades", t =>
                        {
                            t.Property("DetalleAcceso")
                                .HasColumnName("Terreno_DetalleAcceso");

                            t.Property("FormaTerreno")
                                .HasColumnName("Terreno_FormaTerreno");

                            t.Property("Instalaciones")
                                .HasColumnName("Terreno_Instalaciones");

                            t.Property("MedidasTerrenoAncho")
                                .HasColumnName("Terreno_MedidasTerrenoAncho");

                            t.Property("MedidasTerrenoLargo")
                                .HasColumnName("Terreno_MedidasTerrenoLargo");

                            t.Property("Servicios")
                                .HasColumnName("Terreno_Servicios");

                            t.Property("SuperficieCubierta")
                                .HasColumnName("Terreno_SuperficieCubierta");

                            t.Property("SuperficieTotal")
                                .HasColumnName("Terreno_SuperficieTotal");

                            t.Property("UnidadSuperficieTotal")
                                .HasColumnName("Terreno_UnidadSuperficieTotal");
                        });

                    b.HasDiscriminator().HasValue("Terreno");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Consulta", b =>
                {
                    b.HasOne("Inmobiliaria.Api.Models.Propiedad", "Propiedad")
                        .WithMany()
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.ImagenPropiedad", b =>
                {
                    b.HasOne("Inmobiliaria.Api.Models.Propiedad", "Propiedad")
                        .WithMany("Imagenes")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Inmobiliaria.Api.Models.Propiedad", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
