// Datos para los combos en cascada de Zona Geográfica -> Partido/Localidad del
// formulario de carga. Foco en Buenos Aires (donde realmente opera la inmobiliaria);
// el resto de las provincias tiene sus localidades más conocidas, no un listado exhaustivo.
export const ZONAS_GEOGRAFICAS: string[] = [
  'Bs.As. G.B.A. Zona Norte',
  'Bs.As. G.B.A. Zona Oeste',
  'Bs.As. G.B.A. Zona Sur',
  'Buenos Aires Costa Atlántica',
  'Buenos Aires Interior',
  'Capital Federal',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago Del Estero',
  'Tierra Del Fuego',
  'Tucumán',
];

export const PARTIDOS_POR_ZONA: Record<string, string[]> = {
  'Bs.As. G.B.A. Zona Norte': [
    'Escobar',
    'General San Martín',
    'José C. Paz',
    'Malvinas Argentinas',
    'Pilar',
    'San Fernando',
    'San Isidro',
    'San Miguel',
    'Tigre',
    'Vicente López',
  ],
  'Bs.As. G.B.A. Zona Oeste': [
    'General Rodríguez',
    'Hurlingham',
    'Ituzaingó',
    'La Matanza',
    'Marcos Paz',
    'Merlo',
    'Moreno',
    'Morón',
    'Tres de Febrero',
  ],
  'Bs.As. G.B.A. Zona Sur': [
    'Almirante Brown',
    'Avellaneda',
    'Berazategui',
    'Berisso',
    'Brandsen',
    'Cañuelas',
    'Ensenada',
    'Esteban Echeverría',
    'Ezeiza',
    'Florencio Varela',
    'La Plata',
    'Lanús',
    'Lomas de Zamora',
    'Quilmes',
    'San Vicente',
  ],
  'Buenos Aires Costa Atlántica': [
    'Bahía Blanca',
    'Coronel Dorrego',
    'Coronel de Marina Leonardo Rosales',
    'General Alvarado',
    'General Madariaga',
    'General Pueyrredón (Mar del Plata)',
    'La Costa',
    'Mar Chiquita',
    'Monte Hermoso',
    'Necochea',
    'Pinamar',
    'San Cayetano',
    'Tres Arroyos',
    'Villa Gesell',
  ],
  'Buenos Aires Interior': [
    'Azul',
    'Balcarce',
    'Bolívar',
    'Bragado',
    'Campana',
    'Carmen de Areco',
    'Chacabuco',
    'Chascomús',
    'Chivilcoy',
    'Colón',
    'Coronel Suárez',
    'Dolores',
    'Exaltación de la Cruz',
    'General Belgrano',
    'General Villegas',
    'Junín',
    'Las Flores',
    'Lincoln',
    'Lobos',
    'Luján',
    'Magdalena',
    'Mercedes',
    'Nueve de Julio',
    'Olavarría',
    'Pehuajó',
    'Pergamino',
    'Ramallo',
    'Rauch',
    'Saladillo',
    'Salto',
    'San Andrés de Giles',
    'San Antonio de Areco',
    'San Nicolás',
    'San Pedro',
    'Suipacha',
    'Tandil',
    'Trenque Lauquen',
    'Veinticinco de Mayo',
    'Zárate',
  ],
  'Capital Federal': ['Capital Federal'],
  Catamarca: ['San Fernando del Valle de Catamarca', 'Valle Viejo', 'Santa María', 'Andalgalá', 'Belén', 'Tinogasta'],
  Chaco: ['Resistencia', 'Presidencia Roque Sáenz Peña', 'Villa Ángela', 'Charata', 'Quitilipi', 'General San Martín'],
  Chubut: ['Rawson', 'Comodoro Rivadavia', 'Trelew', 'Puerto Madryn', 'Esquel', 'Gaiman'],
  Córdoba: [
    'Córdoba Capital',
    'Río Cuarto',
    'Villa María',
    'San Francisco',
    'Río Tercero',
    'Villa Carlos Paz',
    'Alta Gracia',
    'Bell Ville',
    'Jesús María',
    'Cosquín',
  ],
  Corrientes: ['Corrientes Capital', 'Goya', 'Mercedes', 'Paso de los Libres', 'Curuzú Cuatiá', 'Santo Tomé'],
  'Entre Ríos': ['Paraná', 'Concordia', 'Gualeguaychú', 'Concepción del Uruguay', 'Gualeguay', 'Villaguay'],
  Formosa: ['Formosa Capital', 'Clorinda', 'Pirané', 'El Colorado'],
  Jujuy: ['San Salvador de Jujuy', 'Palpalá', 'Perico', 'Libertador General San Martín', 'San Pedro'],
  'La Pampa': ['Santa Rosa', 'General Pico', 'Toay', 'Realicó'],
  'La Rioja': ['La Rioja Capital', 'Chilecito', 'Aimogasta', 'Chamical'],
  Mendoza: [
    'Mendoza Capital',
    'Godoy Cruz',
    'Guaymallén',
    'Las Heras',
    'Luján de Cuyo',
    'Maipú',
    'San Rafael',
    'General Alvear',
    'Tunuyán',
    'Rivadavia',
  ],
  Misiones: ['Posadas', 'Oberá', 'Eldorado', 'Puerto Iguazú', 'Apóstoles'],
  Neuquén: ['Neuquén Capital', 'Cutral Có', 'Plottier', 'San Martín de los Andes', 'Villa La Angostura', 'Zapala'],
  'Río Negro': ['Viedma', 'San Carlos de Bariloche', 'General Roca', 'Cipolletti', 'Villa Regina', 'El Bolsón'],
  Salta: ['Salta Capital', 'San Ramón de la Nueva Orán', 'Tartagal', 'Metán', 'Rosario de la Frontera', 'Cafayate'],
  'San Juan': ['San Juan Capital', 'Rawson', 'Rivadavia', 'Chimbas', 'Santa Lucía', 'Pocito', 'Caucete'],
  'San Luis': ['San Luis Capital', 'Villa Mercedes', 'Merlo', 'Justo Daract'],
  'Santa Cruz': ['Río Gallegos', 'Caleta Olivia', 'El Calafate', 'Pico Truncado', 'Puerto Deseado'],
  'Santa Fe': ['Santa Fe Capital', 'Rosario', 'Rafaela', 'Venado Tuerto', 'Reconquista', 'Santo Tomé', 'Villa Constitución'],
  'Santiago Del Estero': ['Santiago del Estero Capital', 'La Banda', 'Termas de Río Hondo', 'Añatuya', 'Frías'],
  'Tierra Del Fuego': ['Ushuaia', 'Río Grande', 'Tolhuin'],
  Tucumán: ['San Miguel de Tucumán', 'Yerba Buena', 'Tafí Viejo', 'Concepción', 'Aguilares', 'Banda del Río Salí'],
};

// Barrios/localidades por partido, solo para "Bs.As. G.B.A. Zona Sur" (donde realmente
// opera la inmobiliaria) — para el resto de las zonas, Barrio/Ciudad sigue siendo un campo
// de texto libre. No es una lista exhaustiva, pero cubre las localidades más conocidas.
export const BARRIOS_POR_PARTIDO_ZONA_SUR: Record<string, string[]> = {
  Quilmes: ['Bernal', 'Bernal Oeste', 'Don Bosco', 'Ezpeleta', 'Ezpeleta Oeste', 'Quilmes', 'Quilmes Oeste', 'San Francisco Solano'],
  Avellaneda: ['Avellaneda', 'Crucecita', 'Dock Sud', 'Gerli', 'Piñeyro', 'Sarandí', 'Villa Domínico', 'Wilde'],
  Lanús: ['Lanús Este', 'Lanús Oeste', 'Monte Chingolo', 'Remedios de Escalada', 'Valentín Alsina', 'Villa Caraza', 'Villa Jardín'],
  'Lomas de Zamora': [
    'Banfield',
    'Villa Fiorito',
    'Ingeniero Budge',
    'Llavallol',
    'Lomas de Zamora',
    'Temperley',
    'Turdera',
    'Villa Centenario',
  ],
  'Almirante Brown': [
    'Adrogué',
    'Burzaco',
    'Claypole',
    'Don Orione',
    'Glew',
    'José Mármol',
    'Longchamps',
    'Rafael Calzada',
    'San José',
  ],
  Berazategui: ['Berazategui', 'Berazategui Oeste', 'El Pato', 'Hudson', 'Plátanos', 'Ranelagh', 'Sourigues', 'Villa España'],
  'Florencio Varela': [
    'Florencio Varela',
    'Bosques',
    'Gobernador Julio A. Costa',
    'Ingeniero Allan',
    'San Juan Bautista',
    'Villa Vatteone',
    'Zeballos',
  ],
  'Esteban Echeverría': ['Monte Grande', '9 de Abril', 'Canning', 'El Jagüel', 'Luis Guillón', 'Santa Marina'],
  Ezeiza: ['Ezeiza', 'Carlos Spegazzini', 'La Unión', 'Santa Catalina', 'Tristán Suárez'],
  'San Vicente': ['San Vicente', 'Alejandro Korn', 'Domselaar'],
  Cañuelas: ['Cañuelas', 'Alejandro Petión', 'Máximo Paz', 'Uribelarrea', 'Vicente Casares'],
  Brandsen: ['Brandsen', 'Jeppener', 'Oliden', 'Ferrari'],
  'La Plata': [
    'La Plata',
    'Abasto',
    'City Bell',
    'Gonnet',
    'Los Hornos',
    'Melchor Romero',
    'Ringuelet',
    'Tolosa',
    'Villa Elisa',
  ],
  Berisso: ['Berisso', 'El Carmen', 'Los Talas', 'Villa Progreso'],
  Ensenada: ['Ensenada', 'Punta Lara'],
};
